### ISSUE TITLE
feat: Enhance Provider DI System with Automatic Injection Support

### ISSUE THREAD

**Issue by MarkShawn2020** [oh-my-commit/oh-my-commit#3]
## Issue Description

Currently, the system cannot automatically apply decorators and dependency injection when loading compiled JS providers. This requires manual injection of dependencies, which is not ideal for maintainability and scalability.

## Current Implementation

```typescript
// In ProviderRegistry.loadProviderFromFile
const provider = new Provider() as BaseGenerateCommitProvider;
provider.logger = Container.get(TOKENS.Logger); // Manual injection
```

## Technical Challenges

1. Decorator metadata is lost after TypeScript compilation
2. Dynamic imports via `jiti` may not preserve decorator information
3. Manual dependency injection is currently required

### Approach 1: Enhanced Metadata System (Confidence: 80%)

1. Implement `reflect-metadata` for decorator information preservation
2. Create a custom decorator factory for runtime decoration
3. Utilize TypeScript's experimental decorator features

### Approach 2: Provider Interface Enhancement (Confidence: 70%)

1. Define a strict provider interface
2. Implement a provider factory pattern
3. Add runtime validation and injection

## Implementation Steps

1. Add `reflect-metadata` dependency
2. Create decorator factory system
3. Enhance provider loading mechanism
4. Add runtime validation
5. Update documentation

## Success Criteria

- [ ] Automatic dependency injection works for compiled providers
- [ ] No manual injection required in `loadProviderFromFile`
- [ ] Maintains backward compatibility
- [ ] Comprehensive error handling
- [ ] Documentation for provider developers
